import { channelInfo } from '../lib/messageConfig.js';
import { fakeQuoted } from '../lib/fquoted.js';

const truths = [
  "Quel est ton plus grand secret que personne ici ne sait ?",
  "Quelle est la dernière personne à qui tu as envoyé un message compromettant ?",
  "Si tu pouvais échanger ta vie avec un membre de ce groupe pour 24h, ce serait qui ?",
  "Quelle est la chose la plus ridicule que tu as faite par amour ?",
  "As-tu déjà menti dans ce groupe ? Si oui, à quel sujet ?",
  "Quelle est la personne que tu évites le plus et pourquoi ?",
  "Quel est ton plus gros red flag (ou comportement) que tu as déjà eu ?",
  "À quoi penses-tu vraiment quand tu dis que “ça va” ?",
  "Quelle est la rumeur que tu aimerais le plus démentir ?",
  "Quel est le truc le plus gênant que tu as googlé ?",
  "Qui t’a le plus influencé(e) récemment, et comment ?",
  "Si ton téléphone pouvait parler, qu’est-ce qu’on découvrirait ?",
  "Quelle est ta plus grande faiblesse dans une relation ?",
  "Quelle est ta plus grande peur quand tu entres en soirée / en groupe ?",
  "Quel est ton plus grand fantasme (au choix : romantique ou insolent) ?",
  "Quelle habitude de ta part rend quelqu’un dingue, mais tu t’en rends pas compte ?",
  "Quelle est la chose que tu ferais différemment si tu pouvais remonter le temps ?",
  "Quel est ton plus grand “souci” avec l’authenticité ?",
  "Quelle est la personne dont tu as le plus envie de te rapprocher (même juste un peu) ?",
  "Quelle est ta pensée la plus méchante que tu as eue (mais que tu ne dis jamais) ?",
  "Quel secret as-tu gardé parce que tu avais peur d’être jugé(e) ?",
  "Quel est le mensonge le plus “gentil” que tu as déjà dit ?",
  "Quel est ton regret numéro 1 dans les derniers mois ?",
  "Quelle est la chose que tu as tendance à surinterpréter ?",
  "As-tu déjà eu un coup de cœur pour quelqu’un que tu ne devais pas ? Explique.",
  "Quelle est ta plus grande obsession (même pas très fière) ?",
  "Si tu pouvais supprimer un souvenir de ta tête, ce serait lequel ?",
  "Qu’est-ce que tu n’avoues à personne parce que tu as peur du regard des autres ?",
  "Quelle est la chose la plus bizarre que tu as faite pour impressionner quelqu’un ?",
  "Qui dans ce groupe te fait le plus rire et pourquoi ?",
  "Quel est ton plus grand “je le savais” dans une histoire d’amour ?",
  "Quelle est la dernière fois où tu as stalké quelqu’un (et sur quoi) ?",
  "À quel point tu es honnête 1 à 10 avec les autres ?",
  "Quel est ton plus gros complexe et comment tu le caches ?",
  "Quel est le compliment que tu aimerais qu’on te fasse souvent ?",
  "Quelle est ta pire habitude en amour ?",
  "Quelle personne te donne le plus envie de te dépasser ?",
  "Quelle est la vérité que tu dis seulement quand tu es très fatigué(e) ?",
  "Quelle est la chose la plus impulsive que tu as faite et que tu regrettes un peu ?",
  "Si tu devais choisir : amour ou liberté ? Pourquoi ?",
  "Quelle est la phrase que tu dis souvent mais qui te décrit le mieux ?",
  "Qu’est-ce que tu aimerais que quelqu’un comprenne enfin sur toi ?",
  "Quelle est ta plus grande jalousie (même légère) ?",
  "Quelle est la vérité la plus romantique que tu n’oses pas dire ?",
  "As-tu déjà eu un rendez-vous “bizarre” ? Raconte sans trop de détails.",
  "Quel est ton plus gros “crush” récent (même si ça ne dure pas) ?",
  "Quel est ton style d’attachement : plutôt fuyant(e) ou plutôt collant(e) ?",
  "Quelle est la personne que tu as ghostée ? (Et pourquoi) ?",
  "Quelle est la chose que tu fais quand tu es en stress ?",
  "Tu préfères les gens qui sont directs ou ceux qui tournent autour ?",
  "Quelle est ta plus grande peur d’être rejeté(e) sur un point précis ?",
  "Quel est le dernier truc que tu as fait pour plaire et tu l’assumes ?",
  "Quelle est la vérité que tu as dite à moitié (et pas toute entière) ?",
  "Si tu pouvais voir ton avenir amoureux à 1 an : ce serait comment ?",
  "Quelle est la chose que tu cherches chez quelqu’un mais que tu ne dis jamais ?",
  "Qu’est-ce que tu fais pour te rassurer quand ça va mal ?",
  "Quel est ton plus grand “what if” ?",
  "Quelle est la décision la plus compliquée que tu as prise pour protéger ton cœur ?",
  "Quelle est la chose qui te rend jaloux(se) sans que tu le montres ?",
  "Tu as déjà été en concurrence sans le dire ? Pour quoi ?",
  "Quelle est la vérité que tu as peur d’entendre sur toi ?",
  "Quel est le moment où tu as senti que tu changeais vraiment ?",
  "Quelle est la chose que tu as honte d’aimer regarder / écouter ?",
  "Quel est le compliment qui t’a le plus touché(e) récemment ?",
  "Quel est ton plus grand fantasme de situation (sans détails explicites) ?",
  "Tu as déjà “embelli” une histoire pour paraître plus cool ?",
  "Quelle est la vérité qui te met mal à l’aise quand on te connaît mieux ?",
  "Si tu avais une machine à voyager dans le temps : quel moment tu revisites ?",
  "Quel est ton plus grand regret niveau amitié ?",
  "Qu’est-ce qui t’énerve mais que tu ne dis pas frontalement ?",
  "Quel est ton style de communication : tu réponds vite ou tu fais attendre ?",
  "Quelle est la personne à qui tu penses souvent mais que tu n’oses pas contacter ?",
  "Quel est ton plus grand “c’est pas grave” qui ne l’est pas ?",
  "As-tu déjà eu une relation où tu donnais plus que l’autre ?",
  "Quelle est ton plus grand besoin affectif ?",
  "Quelle est la chose que tu fais pour “tester” les gens ?",
  "Tu as déjà utilisé le silence comme arme ?",
  "Quelle est la vérité que tu cacherais même à quelqu’un que tu aimes ?",
  "Qui te connaît le moins mais croit te connaître parfaitement ?",
  "Quel est ton plus grand “excuse” pour ne pas agir ?",
  "Quelle est la chose que tu refuses d’admettre sur toi ?",
  "Si tu devais écrire une autobiographie en 5 mots : lesquels ?",
  "Quelle est la chose la plus dangereuse que tu as laissée entrer dans ta vie ?",
  "Quel est le moment où tu as compris que tu avais besoin d’aide ?",
  "Quelle est ta faiblesse quand tu es fatigué(e) ?",
  "Qu’est-ce que tu mens à toi-même pour tenir ?",
  "Quelle est la meilleure décision que tu as prise pour ton avenir ?",
  "Quel est ton plus grand “redemption arc” (tu te bats pour changer quoi) ?",
  "Quel est ton plus grand plaisir coupable ?",
  "Quel est ton plus gros ennemi intérieur (peur, doute, etc.) ?",
  "Si tu pouvais changer une chose sur toi en une journée : laquelle ?",
  "Quelle est ton plus grande contradiction ?",
  "Quelle est la phrase que tu aimerais entendre de quelqu’un en particulier ?",
  "Quel secret te ferait perdre des gens si tu le disais ?",
  "Quel est ton pire mensonge par omission ?",
  "Tu as déjà eu une relation “par habitude” ? Raconte le ressenti.",
  "Quelle est la chose la plus honnête que tu as déjà dite sans réfléchir ?",
  "Quelle est la vérité sur toi que les gens n’acceptent pas facilement ?",
  "Quel est ton plus grand besoin quand tu te sens seul(e) ?",
  "Quel est ton plus grand “si j’osais” ?",
  "À quelle fréquence tu te compares aux autres ?",
  "Qu’est-ce que tu ressens vraiment quand quelqu’un te plaît ?",
  "Quelle est la chose la plus douce que tu voudrais recevoir mais n’oses pas demander ?",
  "Quel est ton plus grand regret d’avoir trop pardonné ?",
  "Tu as déjà été fier/fière de quelqu’un à un point que tu n’as pas montré ?",
  "Quelle est la vérité la plus simple que tu oublies souvent ?",
  "Quel est ton vrai rêve que tu gardes pour plus tard ?",
  "Quelle est ta plus grande leçon de vie récente ?",
  "Quelle est la vérité que tu as sur quelqu’un mais que tu ne diras pas ?",
  "Si on vérifiait ton navigateur, qu’est-ce qu’on découvrirait ?",
  "Quel est ton plus grand “mauvais timing” ?",
  "Quel est ton plus grand “et si” niveau carrière / études ?",
  "Quel est ton plus grand défi émotionnel aujourd’hui ?",
  "Tu préfères être aimé(e) pour qui tu es ou pour qui tu montres ?",
  "Quelle est la vérité que tu as du mal à dire “je m’excuse” ?",
  "Quel est ton plus gros trigger quand on te critique ?",
  "Quel est ton plus grand secret sur ton futur ?"
];

const actions = [
  "Envoie un message vocal de 10 secondes où tu chantes ta chanson préférée à fond.",
  "Change ton statut WhatsApp par 'Je suis amoureux/se d'un bot' pendant 1 heure.",
  "Fais une déclaration d'amour théâtrale à la troisième personne qui apparaît dans ta liste de contacts.",
  "Envoie le mème le plus bizarre de ta galerie sans donner d'explication.",
  "Met en photo de profil une image choisie par le groupe pendant 30 minutes.",

  "Fais une liste de 5 choses qui te rendent heureux(se), puis lis-la à voix haute.",
  "Envoie un message à quelqu’un en “Merci pour ton existence” (sans explication).",
  "Prends une photo de ton coin le plus étrange à la maison et envoie-la.",
  "Fais un compliment très précis à la personne de ton choix dans le groupe (sans demander).",
  "Écris un mini poème en 4 lignes sur “l’été” et envoie-le.",
  "Réponds à une question du groupe avec 1 seul mot (au lieu de plusieurs).",
  "Fais 20 secondes de danse “mauvais freestyle” et décris ton énergie après.",
  "Change ton fond d’écran par quelque chose de totalement incohérent pendant 15 minutes.",
  "Imite un animal au choix pendant 30 secondes (sans explication).",
  "Fais un “speech” de 20 secondes comme si tu étais présentateur TV.",
  "Envoie une photo de ton plat / boisson actuelle avec un commentaire dramatique.",
  "Raconte une micro-histoire de 30 secondes : début, rebondissement, fin.",
  "Envoie un message contenant uniquement des emojis pendant 20 secondes.",
  "Fais un “slow clap” (même si c’est ridicule) et dis pourquoi tu applaudis.",
  "Dessine un smiley avec ta main (sur papier) et montre-le au groupe.",
  "Fais semblant d’être en audition et présente-toi en mode personnage.",
  "Écris 3 surnoms que tu aimerais qu’on te donne et envoie-les.",
  "Fais une capture d’écran de ton écran d’accueil et commente-la (sans infos perso).",
  "Réalise un “before/after” en mode : aujourd’hui vs version future (décris).",
  "Envoie le dernier commentaire que tu as laissé sur un post (résume).",
  "Mets un bruitage vocal (ton choix) et laisse-le jouer 5 secondes dans un message.",
  "Fais un jeu de rôle : tu es un guide touristique, on visite ta chambre.",
  "Envoie un message “Je suis une personne différente maintenant” (et ajoute pourquoi).",
  "Change ton nom de profil par un nom inventé et gardes-le 20 minutes.",
  "Fais un ranking : top 3 de tes films/séries, en une seule phrase chacun.",
  "Fais 10 squats et annonce “mission accomplie”.",
  "Envoie une photo d’un objet et raconte son histoire comme si c’était un personnage.",
  "Mets un filtre “stupide” sur une photo (ou envoie une description) pendant 10 minutes.",
  "Fais une déclaration d’amitié en 2 phrases ultra sincères.",
  "Envoie une blague nulle (vraiment nulle) et assume.",
  "Écris une mini lettre à ton moi d’il y a 1 an (5 lignes max).",
  "Fais un “faux appel” à quelqu’un et explique que c’était un test.",
  "Change ton style de phrases : pendant 30 minutes, tu ne dis que des phrases courtes.",
  "Fais une imitation de quelqu’un du groupe (sans méchanceté) pendant 20 secondes.",
  "Envoie un message avec “Je te promets que…” suivi d’une vérité positive.",
  "Raconte ton pire rendez-vous… mais en version comédie (sans détails trop privés).",
  "Mets ton réveil / minuteur sur 1 minute (juste l’annonce) et pendant ce temps : respire et raconte.",
  "Fais un “check” : 3 choses que tu veux faire avant la fin du mois.",
  "Envoie une musique en “soundtrack” pour ta journée (justifie en 1 phrase).",
  "Fais un quiz : pose 5 questions au groupe et laisse-les deviner la réponse.",
  "Fais un “fact check” sur toi : dis un fait vrai + un fait faux (et le groupe devine).",
  "Envoie un message où tu décris ta journée comme un trailer de film.",
  "Fais une “vérification” de ton humeur : 1 couleur + 1 phrase pour l’expliquer.",
  "Fais un compliment à quelqu’un que tu ne compliments jamais.",
  "Envoie une photo d’un endroit moche chez toi et dis pourquoi tu l’aimes quand même.",
  "Fais 30 secondes de respiration guidée (avec tes propres mots).",
  "Réponds au groupe en utilisant seulement des questions pendant 1 minute.",
  "Mets une phrase “mode survie : priorité cœur” dans ton statut pendant 30 minutes.",
  "Crée un surnom pour la personne à gauche (ou celle choisie) et justifie.",
  "Fais une mini chorégraphie sur un rythme imaginaire pendant 10 secondes.",
  "Envoie un message : “Je suis prêt(e) à être jugé(e) sur…” puis choisis un truc.",
  "Fais une devinette sur toi : 3 indices, 1 réponse.",
  "Raconte un moment où tu as été fier/fière de toi (même petit).",
  "Envoie un audio où tu dis ton prénom 5 fois avec 5 émotions différentes.",
  "Fais un “upgrade” : dis 3 façons simples de rendre ta journée meilleure.",
  "Porte un accessoire ridicule pendant 10 minutes (chapeau imaginaire accepté).",
  "Envoie le dernier emoji que tu as utilisé et raconte ce qu’il signifie pour toi.",
  "Fais un mini discours “je veux” (3 objectifs) en 15 secondes.",
  "Change ton fond d’écran pour quelque chose de complètement “hors sujet” pendant 20 minutes.",
  "Envoie une photo d’un miroir (ou description) et dis ce que tu vois en 1 phrase.",
  "Fais une “mise en scène” : décris ta vie comme une série policière.",
  "Fais un “test de personnalité” : dis ton type (au choix) et explique.",
  "Fais une action gentille réelle maintenant (si possible) et dis laquelle.",
  "Envoie un message : “Aujourd’hui je pardonne à…” et complète avec une vérité.",
  "Fais 3 étirements et dis ce que ça te donne comme énergie.",
  "Envoie un message en mode confession (sans trop de détails) en 2 phrases.",
  "Décris ton mood en 1 objet (ex: tempête, café, orage) et explique.",
  "Fais un “roleplay” : tu es un serveur / barista, commande spéciale pour le groupe.",
  "Écris 1 phrase que tu n’osais jamais dire à quelqu’un et envoie-la (anonymisée).",
  "Mets en bio : “Je suis une intrigue” pendant 30 minutes.",
  "Fais un “test” : envoie un message avec une seule intention positive (ex: courage).",
  "Fais un mini tutoriel sur quelque chose de simple que tu sais faire.",
  "Envoie un message où tu remercie quelqu’un pour une qualité (pas pour un service).",
  "Fais une imitation du ton de quelqu’un (de manière drôle) pendant 15 secondes.",
  "Change ton style d’écriture : pendant 10 minutes, tout en majuscules.",
  "Fais 1 compliment à ton reflet (oui, maintenant) et explique pourquoi.",
  "Envoie un message avec un “top secret” mais transforme-le en blague.",
  "Fais un “défi” : annonce une action que tu feras plus tard dans la journée.",
  "Fais un “back to school”: présente-toi comme si tu étais un nouveau élève.",
  "Envoie une photo / description d’un objet “porte-bonheur” et son histoire.",
  "Fais un mini bingo : 5 mots associés à ta personnalité (liste).",
  "Raconte une histoire au groupe en tournant autour d’un secret sans le dire (et finis).",
  "Fais un duo imaginaire : décris comment tu serais en duo avec quelqu’un du groupe.",
  "Envoie un message “Je te choisis” mais avec une raison totalement inattendue.",
  "Fais une annonce style radio (10 secondes) pour un “événement” dans ta vie.",
  "Envoie un mème inventé : décris le mème en texte (caption + image imaginaire).",
  "Fais un “après coup” : raconte ce que tu aurais dit si tout avait changé.",
  "Change ton statut en “Focus : cœur + humour” pendant 25 minutes.",
  "Fais 20 secondes de “mode robot” en parlant, puis reviens normal.",
  "Envoie une photo de ton meilleur coin de lumière et dis ta vibe.",
  "Fais une “carte postale” en 2 phrases depuis un endroit fictif.",
  "Raconte un compliment que tu aimerais recevoir et de qui ça pourrait venir.",
  "Envoie un audio où tu lis un message en mode acteur dramatique.",
  "Fais un “audit” : dis 3 choses que tu veux arrêter de faire bientôt.",
  "Envoie une déclaration positive à quelqu’un du groupe (sans pression).",
  "Fais un “challenge” : dis ton plus gros objectif pour cette semaine en 1 phrase.",
  "Fais un “mini vlog” de 20 secondes : caméra imaginaire, narration.",
  "Envoie une phrase de film romantique (pas trop cringe) et assume.",
  "Fais un gage : écris ton prénom + un adjectif en mode slogan (ex: “Camille solaire”).",
  "Fais une liste : 3 choses que tu veux apprendre bientôt.",
  "Fais une “confession” drôle : dis un fait un peu honteux mais innocent.",
  "Change ton fond d’écran par un écran noir avec une seule phrase au centre.",
  "Envoie un message avec un “assume” (ex: “J’assume que…”).",
  "Fais une mini prière/affirmation de 10 secondes (style humour accepté).",
  "Fais un “speedrun” de ta journée en 15 secondes (par étapes).",
  "Envoie une photo (ou description) de ton endroit où tu te sens bien.",
  "Fais un “portrait verbal” de toi : 5 adjectifs, pas plus.",
  "Fais un “duo” : choisis une chanson pour ta personnalité et explique.",
  "Envoie un message : “Je suis maintenant en mode…” et complète avec ton humeur.",
  "Fais un test : écris une phrase et inverses les mots (ex: “je suis” -> “suis je”).",
  "Fais une micro performance : 10 secondes de théâtre “émotion au hasard”.",
  "Envoie une liste de 3 choses que tu veux que le groupe te dise ce soir.",
  "Change ton statut en “Team chaos doux” pendant 20 minutes.",
  "Envoie un message vocal où tu dis 3 choses que tu apprécies chez quelqu’un.",
  "Fais un “rituel” : 30 secondes de gratitude (3 choses).",
  "Mets une photo de profil choisie par le groupe pendant 30 minutes (action répétable)."
];


export default async function vdaCommand(message, client, { args }) {
  const chat = message.key.remoteJid;
  if (!chat.endsWith('@g.us')) {
    return await client.sendMessage(chat, {
      text: "> ❌ *Cette commande est uniquement utilisable dans un groupe !*",
      ...channelInfo
    }, { quoted: fakeQuoted });
  }

  const choice = args[0]?.toLowerCase();

  if (choice !== "action" && choice !== "verite" && choice !== "vérité") {
    return await client.sendMessage(chat, {
      text: `*⟬🎮⟭ 𝐀𝐂𝐓𝐈𝐎𝐍 𝐎𝐔 𝐕𝐄́𝐑𝐈𝐓𝐄́*\n\n> Choisissez votre destin en tapant :\n👉 \`vda action\`\n👉 \`vda verite\``,
      ...channelInfo
    }, { quoted: fakeQuoted });
  }

  if (choice === "action") {
    const randomAction = actions[Math.floor(Math.random() * actions.length)];
    await client.sendMessage(chat, {
      text: `〘〘 *𝐌𝐎𝐃𝐄 𝐀𝐂𝐓𝐈𝐎𝐍* 〙〙\n\n> ${randomAction}\n\n*_Tu as 2 minutes pour t'exécuter ou tu auras un gage !_*`,
      ...channelInfo
    }, { quoted: fakeQuoted });
  } else {
    const randomTruth = truths[Math.floor(Math.random() * truths.length)];
    await client.sendMessage(chat, {
      text: `〘〘 *𝐌𝐎𝐃𝐄 𝐕𝐄́𝐑𝐈𝐓𝐄́* 〙〙\n\n> ${randomTruth}\n\n*_Dis la vérité, rien que la vérité !_*`,
      ...channelInfo
    }, { quoted: fakeQuoted });
  }
}
